language: android
jdk:
- oraclejdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - android-22
    - extra-android-m2repository  
    - sys-img-armeabi-v7a-android-22

before_install:
- chmod +x gradlew

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

script:
- ./gradlew assembleDebug --stacktrace
- ./gradlew jacocoTestReport --info
after_success:
- bash <(curl -s https://codecov.io/bash)

